
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 26nandtanu
 */
public class CalcFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalcFrame
     */
    public CalcFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(205, 205, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        ansTF = new javax.swing.JTextField();
        clearBT = new javax.swing.JButton();
        percentageBT = new javax.swing.JButton();
        divBT = new javax.swing.JButton();
        multBT = new javax.swing.JButton();
        cosBT = new javax.swing.JButton();
        sinBT = new javax.swing.JButton();
        tanBT = new javax.swing.JButton();
        subBT = new javax.swing.JButton();
        cubeBT = new javax.swing.JButton();
        sqrBT = new javax.swing.JButton();
        powerBT = new javax.swing.JButton();
        addBT = new javax.swing.JButton();
        sqrtBT = new javax.swing.JButton();
        absBT = new javax.swing.JButton();
        factBT = new javax.swing.JButton();
        inputBTF = new javax.swing.JTextField();
        inputATF = new javax.swing.JTextField();
        warningTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setForeground(new java.awt.Color(204, 204, 255));

        titleLBL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(102, 0, 204));
        titleLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLBL.setText("Tanushka's Calculator");
        titleLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titleLBL.setName(""); // NOI18N

        ansTF.setEditable(false);
        ansTF.setBackground(new java.awt.Color(153, 153, 153));
        ansTF.setFont(new java.awt.Font("Proxy 9", 0, 24)); // NOI18N
        ansTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        clearBT.setBackground(new java.awt.Color(153, 153, 255));
        clearBT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        clearBT.setForeground(new java.awt.Color(102, 102, 102));
        clearBT.setText("Clear");
        clearBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        clearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTActionPerformed(evt);
            }
        });

        percentageBT.setBackground(new java.awt.Color(153, 153, 255));
        percentageBT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        percentageBT.setForeground(new java.awt.Color(102, 102, 102));
        percentageBT.setText("%");
        percentageBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        percentageBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageBTActionPerformed(evt);
            }
        });

        divBT.setBackground(new java.awt.Color(153, 153, 255));
        divBT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        divBT.setForeground(new java.awt.Color(102, 102, 102));
        divBT.setText("/");
        divBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        divBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBTActionPerformed(evt);
            }
        });

        multBT.setBackground(new java.awt.Color(153, 153, 255));
        multBT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        multBT.setForeground(new java.awt.Color(102, 102, 102));
        multBT.setText("x");
        multBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        multBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multBTActionPerformed(evt);
            }
        });

        cosBT.setBackground(new java.awt.Color(153, 153, 255));
        cosBT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cosBT.setForeground(new java.awt.Color(102, 102, 102));
        cosBT.setText("cos");
        cosBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        cosBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosBTActionPerformed(evt);
            }
        });

        sinBT.setBackground(new java.awt.Color(153, 153, 255));
        sinBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sinBT.setForeground(new java.awt.Color(102, 102, 102));
        sinBT.setText("sin");
        sinBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        sinBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinBTActionPerformed(evt);
            }
        });

        tanBT.setBackground(new java.awt.Color(153, 153, 255));
        tanBT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tanBT.setForeground(new java.awt.Color(102, 102, 102));
        tanBT.setText("tan");
        tanBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        tanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanBTActionPerformed(evt);
            }
        });

        subBT.setBackground(new java.awt.Color(153, 153, 255));
        subBT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        subBT.setForeground(new java.awt.Color(102, 102, 102));
        subBT.setText("-");
        subBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        subBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBTActionPerformed(evt);
            }
        });

        cubeBT.setBackground(new java.awt.Color(153, 153, 255));
        cubeBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cubeBT.setForeground(new java.awt.Color(102, 102, 102));
        cubeBT.setText("^3");
        cubeBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        cubeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeBTActionPerformed(evt);
            }
        });

        sqrBT.setBackground(new java.awt.Color(153, 153, 255));
        sqrBT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sqrBT.setForeground(new java.awt.Color(102, 102, 102));
        sqrBT.setText("^2");
        sqrBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        sqrBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrBTActionPerformed(evt);
            }
        });

        powerBT.setBackground(new java.awt.Color(153, 153, 255));
        powerBT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        powerBT.setForeground(new java.awt.Color(102, 102, 102));
        powerBT.setText("^");
        powerBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        powerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerBTActionPerformed(evt);
            }
        });

        addBT.setBackground(new java.awt.Color(153, 153, 255));
        addBT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        addBT.setForeground(new java.awt.Color(102, 102, 102));
        addBT.setText("+");
        addBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        sqrtBT.setBackground(new java.awt.Color(153, 153, 255));
        sqrtBT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        sqrtBT.setForeground(new java.awt.Color(102, 102, 102));
        sqrtBT.setText("sqrt");
        sqrtBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        sqrtBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtBTActionPerformed(evt);
            }
        });

        absBT.setBackground(new java.awt.Color(153, 153, 255));
        absBT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        absBT.setForeground(new java.awt.Color(102, 102, 102));
        absBT.setText("abs");
        absBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        absBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absBTActionPerformed(evt);
            }
        });

        factBT.setBackground(new java.awt.Color(153, 153, 255));
        factBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        factBT.setForeground(new java.awt.Color(102, 102, 102));
        factBT.setText("x!");
        factBT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        factBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factBTActionPerformed(evt);
            }
        });

        inputBTF.setBackground(new java.awt.Color(204, 204, 204));
        inputBTF.setFont(new java.awt.Font("Proxy 9", 0, 24)); // NOI18N
        inputBTF.setForeground(new java.awt.Color(102, 102, 102));
        inputBTF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        inputATF.setBackground(new java.awt.Color(204, 204, 204));
        inputATF.setFont(new java.awt.Font("Proxy 9", 0, 24)); // NOI18N
        inputATF.setForeground(new java.awt.Color(102, 102, 102));
        inputATF.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        inputATF.setToolTipText("");

        warningTF.setEditable(false);
        warningTF.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        warningTF.setForeground(new java.awt.Color(255, 0, 0));
        warningTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        warningTF.setText("Sine, Cosine, Tangent, Absolute Value, Square, Cube, Square Root, and Factorial ONLY WORK ON TEXT FIELD ON LEFT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(titleLBL)
                .addGap(0, 161, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputATF, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputBTF)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ansTF)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sinBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tanBT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(sqrBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(powerBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(absBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(cubeBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sqrtBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(multBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(percentageBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(factBT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(subBT, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                            .addComponent(divBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(clearBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningTF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputBTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputATF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(ansTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sinBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(absBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sqrBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cubeBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(percentageBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sqrtBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powerBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(warningTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        titleLBL.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sinBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinBTActionPerformed
        String tempa = inputATF.getText();
        double a = Double.parseDouble(tempa);
        double sin = Math.sin(a);
        ansTF.setText(Double.toString(sin));
    }//GEN-LAST:event_sinBTActionPerformed

    private void cosBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosBTActionPerformed
        String tempa = inputATF.getText();
        double a = Double.parseDouble(tempa);
        double cos = Math.cos(a);
        ansTF.setText(Double.toString(cos));
    }//GEN-LAST:event_cosBTActionPerformed

    private void tanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanBTActionPerformed
        String tempa = inputATF.getText();
        double a = Double.parseDouble(tempa);
        double tan = Math.tan(a);
        ansTF.setText(Double.toString(tan));
    }//GEN-LAST:event_tanBTActionPerformed

    private void absBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absBTActionPerformed
        String tempa = inputATF.getText();
        double a = Double.parseDouble(tempa);
        double abs = Math.abs(a);
        ansTF.setText(Double.toString(abs));
    }//GEN-LAST:event_absBTActionPerformed

    private void sqrBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrBTActionPerformed
        String tempa = inputATF.getText();
        double a = Double.parseDouble(tempa);
        double square = a*a;
        ansTF.setText(Double.toString(square));
    }//GEN-LAST:event_sqrBTActionPerformed

    private void cubeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeBTActionPerformed
        String tempa = inputATF.getText();
        double a = Double.parseDouble(tempa);
        double cube = a*a*a;
        ansTF.setText(Double.toString(cube));
    }//GEN-LAST:event_cubeBTActionPerformed

    private void powerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerBTActionPerformed
        String tempa = inputATF.getText();
        String tempb = inputBTF.getText();
        double a = Double.parseDouble(tempa);
        double b = Double.parseDouble(tempb);
        double power = Math.pow(a, b);
        ansTF.setText(Double.toString(power));
    }//GEN-LAST:event_powerBTActionPerformed

    private void sqrtBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtBTActionPerformed
        String tempa = inputATF.getText();
        double a = Double.parseDouble(tempa);
        double sqrt = Math.sqrt(a);
        ansTF.setText(Double.toString(sqrt));
    }//GEN-LAST:event_sqrtBTActionPerformed

    private void clearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTActionPerformed
        inputATF.setText("");
        inputBTF.setText("");
        ansTF.setText("");
    }//GEN-LAST:event_clearBTActionPerformed

    private void percentageBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageBTActionPerformed
        String tempa = inputATF.getText();
        String tempb = inputBTF.getText();
        double a = Double.parseDouble(tempa);
        double b = Double.parseDouble(tempb);
        double modulus = a%b;
        ansTF.setText(Double.toString(modulus));
    }//GEN-LAST:event_percentageBTActionPerformed

    private void divBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBTActionPerformed
        String tempa = inputATF.getText();
        String tempb = inputBTF.getText();
        double a = Double.parseDouble(tempa);
        double b = Double.parseDouble(tempb);
        double ans = a/b;
        ansTF.setText(Double.toString(ans));
    }//GEN-LAST:event_divBTActionPerformed

    private void multBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multBTActionPerformed
        String tempa = inputATF.getText();
        String tempb = inputBTF.getText();
        double a = Double.parseDouble(tempa);
        double b = Double.parseDouble(tempb);
        double ans = a*b;
        ansTF.setText(Double.toString(ans));
    }//GEN-LAST:event_multBTActionPerformed

    private void subBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBTActionPerformed
        String tempa = inputATF.getText();
        String tempb = inputBTF.getText();
        double a = Double.parseDouble(tempa);
        double b = Double.parseDouble(tempb);
        double ans = a-b;
        ansTF.setText(Double.toString(ans));
    }//GEN-LAST:event_subBTActionPerformed

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        String tempa = inputATF.getText();
        String tempb = inputBTF.getText();
        double a = Double.parseDouble(tempa);
        double b = Double.parseDouble(tempb);
        double ans = a+b;
        ansTF.setText(Double.toString(ans));
    }//GEN-LAST:event_addBTActionPerformed

    private void factBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factBTActionPerformed
        String tempa = inputATF.getText();
        double a = Double.parseDouble(tempa);
        double ans = 1;
        for(double i=a; i>0; i--){
            ans = ans*i;
        }
        ansTF.setText(Double.toString(ans));
    }//GEN-LAST:event_factBTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton absBT;
    private javax.swing.JButton addBT;
    private javax.swing.JTextField ansTF;
    private javax.swing.JButton clearBT;
    private javax.swing.JButton cosBT;
    private javax.swing.JButton cubeBT;
    private javax.swing.JButton divBT;
    private javax.swing.JButton factBT;
    private javax.swing.JTextField inputATF;
    private javax.swing.JTextField inputBTF;
    private javax.swing.JButton multBT;
    private javax.swing.JButton percentageBT;
    private javax.swing.JButton powerBT;
    private javax.swing.JButton sinBT;
    private javax.swing.JButton sqrBT;
    private javax.swing.JButton sqrtBT;
    private javax.swing.JButton subBT;
    private javax.swing.JButton tanBT;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JTextField warningTF;
    // End of variables declaration//GEN-END:variables
}
